<?php

function favorites_menu() {
  $items = array();
  $favorites = get_favorites();
  foreach ($favorites as $favorite_type => $favorites) {
    $items['favorite/' . $favorite_type] = array(
      'title' => $favorite_type,
      'page callback' => 'show_favorites',
      'page arguments' => array(
        $favorite_type
      ),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM
    );
  }
  return $items;
}

function get_favorites() {
    $my_favorites['movies'] = array(
          'Cliffhanger',
          'Altered Beast',
          'Leviathan'
        );
    $my_favorites['books'] = array(
          'Godel, Escher, Bach: An Eternal Golden Braid',
          'Farenheit 451',
          'Eragon'
        );
    $my_favorites['songs'] = array(
          'Hunger Strike by Estradasphere',
          'The 7 by Secret Chiefs 3',
          'Not Alone by Dub Trio'
    );
    return $my_favorites;
}

function show_favorites($arg) {
$fav_list = get_favorites();
$favorite_type = $fav_list[$arg];
$text = 'Here is your list of favorite ' . $arg . ':<ul>';
foreach ($favorite_type as $fav_list_item) {
    $text .= '<li>' . $fav_list_item . '</li>';
};
$text .= "</ul>";

return $text;
}
